### ISSUE TITLE
3DTOUCH with MONSTER8 with klipper

### ISSUE THREAD

**Issue by selimayaz** [makerbase-mks/MKS-Monster8#10]
Hello, i can't get work 3dtouch with mosnter8. i think i need exact pin names. Can anybody help me? Thnaks.

"
[bltouch]
sensor_pin = PC3
control_pin = PA8
pin_move_time = 0.3
stow_on_each_sample = false
probe_with_touch_mode = false
pin_up_touch_mode_reports_triggered = true
x_offset = -55
y_offset = 0
z_offset = 1.70
samples = 2
sample_retract_dist = 2
samples_result = average
"

BLTouch failed to deploy
Failed to verify BLTouch probe is raised; retrying.
Stats 44.6: gcodein=0 mcu: mcu_awake=0.002 mcu_task_avg=0.000007 mcu_task_stddev=0.000007 bytes_write=7386 bytes_read=8980 bytes_retransmit=9 bytes_invalid=0 send_seq=389 receive_seq=389 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=26 freq=168001480  heater_bed: target=0 temp=17.9 pwm=0.000 sysload=0.21 cputime=1.272 memavail=1685996 print_time=52.669 buffer_time=0.000 print_stall=0 extruder: target=0 temp=17.0 pwm=0.000
Stats 45.6: gcodein=0 mcu: mcu_awake=0.002 mcu_task_avg=0.000007 mcu_task_stddev=0.000007 bytes_write=7420 bytes_read=9111 bytes_retransmit=9 bytes_invalid=0 send_seq=392 receive_seq=392 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=8 freq=168001465  heater_bed: target=0 temp=17.8 pwm=0.000 sysload=0.19 cputime=1.287 memavail=1685996 print_time=52.669 buffer_time=0.000 print_stall=0 extruder: target=0 temp=16.9 pwm=0.000
Failed to verify BLTouch probe is raised; retrying.
Stats 46.6: gcodein=0 mcu: mcu_awake=0.001 mcu_task_avg=0.000006 mcu_task_stddev=0.000005 bytes_write=7552 bytes_read=9349 bytes_retransmit=9 bytes_invalid=0 send_seq=400 receive_seq=400 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=18 freq=168001496  heater_bed: target=0 temp=18.0 pwm=0.000 sysload=0.19 cputime=1.310 memavail=1686264 print_time=52.669 buffer_time=0.000 print_stall=0 extruder: target=0 temp=16.9 pwm=0.000
Multi-probe end
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/probe.py", line 93, in _handle_command_error
    self.multi_probe_end()
  File "/home/pi/klipper/klippy/extras/probe.py", line 102, in multi_probe_end
    self.mcu_probe.multi_probe_end()
  File "/home/pi/klipper/klippy/extras/bltouch.py", line 183, in multi_probe_end
    self.verify_raise_probe()
  File "/home/pi/klipper/klippy/extras/bltouch.py", line 137, in verify_raise_probe
    "BLTouch failed to raise probe")
CommandError: BLTouch failed to raise probe

**Comment by MKS-hosiey** [comment]
sensor_pin=!PC3
